---
- name: Run zookeeper container
  become: yes
  shell: |
    set -e
    set -x
    docker run -d -p 2181:2181 -p 2888:2888 -p 3888:3888 \
               --restart always \
               --name zuul_zoo \
               zookeeper:3.4
  args:
    executable: /bin/bash
